general:
  token: ТОКЕН ВК
  group_name: Имя группы
  dir_name: Название папки
  logo: Путь к файлу с вотемаркой
  offset: Числовой(С какой страницы начинать собирать - 20 = 1 страница, например, 100)
  circles: Сколько циклов нужно сделать(1 итерация максимум 100 постов)
  ver_api: Весия API VK на текущий момент
  stop_slova: Стоп слова для фильтрации постов
  wotemark: bool. True/False - наложение вотемарки